name: GitHub-Profile-3D-Contrib

on:
  schedule:
    # Executa todo dia às 18:00 UTC (15:00 no horário de Brasília)
    - cron: "0 18 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate GitHub Profile 3D Contrib
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@latest
        env: # <<< A CORREÇÃO ESTÁ AQUI! MUDAMOS DE "with" PARA "env"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A .
          if git diff --staged --quiet; then
            echo "Nenhuma mudança para commitar, o gráfico 3D já está atualizado."
          else
            git commit -m "chore: Atualiza o gráfico de contribuições 3D"
            git push
          fi
